<?php

namespace Controller;

use Core\Config;

class eatController extends AbstractTableController
{

    protected  $tableName = "eat";

    public function __construct($view)
    {
        parent::__construct($view);

        $this->view->setFolder('eat');
    }

    public function actionShow(array $data)
    {
        parent::actionShow($data); // TODO: Change the autogenerated stub
        $this
            ->view
            ->setTemplate('show')
            ->setData([
                'table' => $this
                    ->table
                    ->reset()
                    ->setPageSize(Config::PAGE_SIZE_DISH)
                    ->getPage($data['get']['page'] ?? 1),
                'fields' => array_diff($this->table->getColumnsNames(), ['id']),
                'comments' => $this->table->getColumnsComments(),
                'type' => $this->getClassName(),
                'pageCount' => $this->table->pageCount()
            ]);
    }

    public function actionAdd(array $data)
    {
        $data['post']['imgeat'] = $_FILES['imgeat']['name'];

        $ext = pathinfo($_FILES['imgeat']['name'], PATHINFO_EXTENSION);

        $id = $this->table->add($data['post']);

        move_uploaded_file(
            $_FILES['imgeat']['tmp_name'],
            "images/eat/$id.$ext"
        );

        $this->redirect('?action=show&type=' . $this->getClassName());
    }

    public function actionEdit(array $data)
    {
        $data['post']['imgeat'] = $_FILES['imgeat']['name'];
        $ext = pathinfo($_FILES['imgeat']['name'], PATHINFO_EXTENSION);
        $id = $data['post']['id'];

        move_uploaded_file(
            $_FILES['imgeat']['tmp_name'],
            "images/eat/$id.$ext"
        );

        parent::actionEdit($data);
    }

    public function actionDel(array $data)
    {
        $id = $data['get']['id'];
        $img = $this->table->get(['id'=>$id])[0]['imgeat'];
        $ext = pathinfo($img, PATHINFO_EXTENSION);
        if(file_exists("images/eat/$id.$ext")){
            unlink("images/eat/$id.$ext");
        }

        parent::actionDel($data);
    }
}
